name: Run Benchmarks
on: 
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Make files
        run: cmake -S . -B build

      - name: Compile C++ source code
        run: cmake --build build

      - name: Run executable
        run: ./build/benchmarks/ols_bench
