name: Run Benchmarks
on: 
  pull_request:

jobs:
  build-and-run:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: brew install ensmallen armadillo cereal

      - name: Create Make files
        run: cmake -S . -B build

      - name: Compile C++ source code
        run: cmake --build build

      - name: Run executable and save output
        run: |
          echo "BENCHMARK_OUTPUT<<EOF" >> \$GITHUB_ENV
          ./build/benchmarks/ols_bench >> \$GITHUB_ENV
          echo "EOF" >> \$GITHUB_ENV

      - name: Comment benchmark output to pr
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message: |
            ### Benchmark Outputs
            ```text
            \${{ env.BENCHMARK_OUTPUT }}
            ```
