name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install armadillo ensmallen cereal

      - name: Configure
        run: cmake -B build -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure
